name: flutter_app_shell_example
description: Example app demonstrating Flutter App Shell framework capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local package dependency
  flutter_app_shell:
    path: ../packages/flutter_app_shell
  
  # Additional dependencies for demo features
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0+1
  smooth_page_indicator: ^1.2.0+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Add any assets here
  assets:
    - .env