name: llms_generator
description: Generate llms.txt files for Flutter App Shell documentation
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  markdown: ^7.2.2    # Official Dart markdown parser
  args: ^2.4.2        # Command-line argument parsing
  path: ^1.9.0        # Path manipulation
  
dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0

executables:
  generate_llms_txt: